# lon low, lat low, lon upp, lat upp
coords:  [-74.01, 40.75, -73.86, 40.88]
time_window: "2021-06-01/2021-09-01"

satellite_config:
  url: "https://planetarycomputer.microsoft.com/api/stac/v1"

  params:
    cloud_cover: 30
    crs: "EPSG:4326"
    chunks: 
      x: 2048
      y: 2048
    dtype: "uint16"

  satellites:
    - collection: ["landsat-c2-l2"]
      platform: ["landsat-8"]
      resolution: 0.00027  # 30 meters
      bands: ['red', 'blue', 'green', 'nir08', 'swir16', 'swir22', 'coastal', 'lwir11']  # last band is always lwir11 
      image_choice: 2
    
    - collection: ["sentinel-2-l2a"]
      platform:
      resolution: 8.98e-05  # 10 meters
      bands: ["B01", "B02", "B03", "B04", "B05", "B06", "B07", "B08", "B8A", "B09", "B11", "B12"]
      image_choice: 1

arcgis_query_config:
  base_url: "https://services5.arcgis.com/GfwWNkhOj9bNBqoJ/arcgis/rest/services/"
  endpoint: "/FeatureServer/0/query"
  name: ["LION", "LION_Node", "nyzd", "nyco", "nysp", "nylh", "nysp_sd", "nyzma"]

soda_api_config:
  base_url: "https://data.cityofnewyork.us/resource"
  datasets:
  - name: "building"
    endpoint: "/5zhs-2jue.json"
  - name: "traffic"
    endpoint: "/7ym2-wayt.json"

gge_engine_config:
  coords: [-74.01, 40.75, -73.86, 40.88]
  time_window: "2021-06-01/2021-09-01"
  crs: "EPSG:4326"
  project: "ee-leolincoln9804"
  collections:
    aq_collections:
      co_collection: 
        name: 'COPERNICUS/S5P/OFFL/L3_CO'
        bands: [
          'CO_column_number_density'
        ]
      hcho_collection: 
        name: 'COPERNICUS/S5P/OFFL/L3_HCHO'
        bands: [
          'tropospheric_HCHO_column_number_density'
        ]
      no2_collection: 
        name: 'COPERNICUS/S5P/OFFL/L3_NO2'
        bands: [
          'NO2_column_number_density',
        ] 
      o3_collection: 
        name: 'COPERNICUS/S5P/OFFL/L3_O3'
        bands: [
          'O3_column_number_density',
        ]
      so2_collection:
        name: 'COPERNICUS/S5P/OFFL/L3_SO2'
        bands: [
          'SO2_column_number_density',
        ]
      aod_collection: 
        name: "MODIS/061/MCD19A2_GRANULES"
        bands: [
          "Optical_Depth_047",
          "Optical_Depth_055",
          "AOD_Uncertainty",
          "AOD_QA",
        ]
    demography_collections:
      population: 
        name: "projects/sat-io/open-datasets/ORNL/LANDSCAN_GLOBAL"
        bands: []